//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolKudasshova320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academies
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Speshiality { get; set; }
        public Nullable<int> YearOfZvanie { get; set; }
    }
}
