//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolKudasshova320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int ID { get; set; }
        public string Nazvanie { get; set; }
        public string Capital { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> People { get; set; }
        public string Continent { get; set; }
    }
}
