//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolKudasshova320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Discipline { get; set; }
        public Nullable<int> ID_Student { get; set; }
        public Nullable<int> ID_Worker { get; set; }
        public string Audience { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
