//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolKudasshova320.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practise320_KudashovaAnnaEntities3 : DbContext
    {
        public Practise320_KudashovaAnnaEntities3()
            : base("name=Practise320_KudashovaAnnaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academies> Academies { get; set; }
        public virtual DbSet<Animal_Kudashova> Animal_Kudashova { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Chair> Chair { get; set; }
        public virtual DbSet<ChairBoss> ChairBoss { get; set; }
        public virtual DbSet<Control_Kudashova> Control_Kudashova { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Countries_Kudashova> Countries_Kudashova { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Kudashova> Flowers_Kudashova { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Student10> Student10 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Licium> Licium { get; set; }
    }
}
